from __future__ import annotations

from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from sqlalchemy import select
from sqlalchemy.orm import Session

from .application.kev_correlation import kev_exposure_matches
from .attack_mapping import techniques_for_family
from .persistence.models import (
    ClusterMemberRecord,
    CollectionRunRecord,
    IndicatorRecord,
    InfrastructureClusterRecord,
    KevEntryRecord,
    ObservationRecord,
    OsintReportRecord,
    RunSourceAttemptRecord,
)


def _top_rows(counter: Counter[str], limit: int = 10) -> list[tuple[str, int]]:
    return counter.most_common(limit)


def _markdown_table(rows: list[tuple[str, int]], heading: str) -> list[str]:
    lines = [f"### {heading}", "", "| Value | Count |", "|---|---:|"]
    lines.extend(f"| {value.replace('|', '\\|')} | {count} |" for value, count in rows)
    lines.append("")
    return lines


def _correlation_rows(
    observations: list[ObservationRecord], indicator_by_id: dict[int, IndicatorRecord]
) -> list[tuple[str, int, str, str, str]]:
    clusters: dict[str, dict[str, Any]] = {}
    for observation in observations:
        metadata: dict[str, Any] = observation.metadata_json or {}
        family = str(metadata.get("malware") or metadata.get("malware_family") or "unlabeled")
        cluster = clusters.setdefault(
            family, {"count": 0, "sources": set(), "types": set(), "tags": Counter()}
        )
        cluster["count"] += 1
        cluster["sources"].add(observation.source)
        indicator = indicator_by_id.get(observation.indicator_id)
        if indicator:
            cluster["types"].add(indicator.indicator_type)
        tags = metadata.get("tags") or []
        if isinstance(tags, list):
            cluster["tags"].update(str(tag) for tag in tags if tag)

    rows = []
    for family, cluster in clusters.items():
        top_tags = ", ".join(tag for tag, _ in cluster["tags"].most_common(3)) or "none"
        rows.append(
            (
                family,
                cluster["count"],
                ", ".join(sorted(cluster["sources"])),
                ", ".join(sorted(cluster["types"])),
                top_tags,
            )
        )
    return sorted(rows, key=lambda row: (-row[1], row[0]))[:15]


def _cluster_section(session: Session, indicator_by_id: dict[int, IndicatorRecord]) -> list[str]:
    clusters = session.scalars(
        select(InfrastructureClusterRecord).order_by(InfrastructureClusterRecord.confidence_score.desc())
    ).all()
    lines = [
        "## Emerging Infrastructure Clusters",
        "",
        "Generated by correlating ASN, TLS certificate, DNS, and malware-family overlap "
        "across enriched indicators. Run `threat-ingest enrich` then `threat-ingest cluster` "
        "to refresh.",
        "",
    ]
    if not clusters:
        lines.extend(["_No clusters detected yet._", ""])
        return lines

    for cluster in clusters:
        members = session.scalars(
            select(ClusterMemberRecord).where(ClusterMemberRecord.cluster_id == cluster.id)
        ).all()
        member_values = sorted(
            indicator_by_id[m.indicator_id].canonical_value
            for m in members
            if m.indicator_id in indicator_by_id
        )
        lines.append(f"### {cluster.cluster_key} — confidence: {cluster.confidence_label} ({cluster.confidence_score})")
        lines.append("")
        lines.append(f"- Members ({len(member_values)}): {', '.join(f'`{v}`' for v in member_values) or 'none'}")
        if cluster.first_observed:
            lines.append(f"- First observed: `{cluster.first_observed.isoformat()}`")
        lines.append("- Why it clustered:")
        for evidence in cluster.evidence_json or []:
            lines.append(f"  - **{evidence['kind']}**: {evidence['detail']}")
        lines.append("")
    return lines


def _kev_section(session: Session, limit: int = 15) -> list[str]:
    entries = session.scalars(
        select(KevEntryRecord).order_by(KevEntryRecord.epss_score.desc()).limit(limit)
    ).all()
    lines = [
        "## Known Exploited Vulnerabilities",
        "",
        "CISA KEV entries ranked by EPSS exploitation probability. Run `threat-ingest "
        "vuln-sync` to refresh; `threat-ingest vuln-lookup CVE-ID` for an on-demand check.",
        "",
    ]
    if not entries:
        lines.extend(["_No KEV catalog synced yet._", ""])
        return lines

    lines.extend(["| CVE | Vendor/Product | EPSS | Ransomware Use | Due Date |", "|---|---|---:|---|---|"])
    for entry in entries:
        epss = f"{entry.epss_score:.3f}" if entry.epss_score is not None else "n/a"
        lines.append(
            f"| {entry.cve_id} | {entry.vendor_project}/{entry.product} | {epss} | "
            f"{'yes' if entry.known_ransomware_use else 'no'} | {entry.due_date.date().isoformat()} |"
        )
    lines.append("")
    return lines


def _exposed_kev_section(session: Session, indicator_by_id: dict[int, IndicatorRecord]) -> list[str]:
    """Cross-references CVE tags surfaced by host enrichment (e.g. Shodan) against
    the local KEV catalog, turning 'this IP is exposed' into 'this IP is exposed to
    a vulnerability that is actively being exploited'."""
    lines = [
        "## Infrastructure Exposing Known Exploited Vulnerabilities",
        "",
        "Host enrichment findings whose reported CVEs also appear in the local KEV "
        "catalog. Run `threat-ingest enrich` and `threat-ingest vuln-sync` to refresh.",
        "",
    ]
    matches = kev_exposure_matches(session)
    if not matches:
        lines.extend(["_No overlap between enriched infrastructure and the KEV catalog yet._", ""])
        return lines

    lines.extend(["| Indicator | CVE | Source |", "|---|---|---|"])
    for value, cve_id, provider in matches:
        lines.append(f"| `{value}` | {cve_id} | {provider} |")
    lines.append("")
    return lines


def _osint_section(session: Session, families: set[str], limit: int = 15) -> list[str]:
    """Lists the latest OSINT research posts and flags which ones mention a
    malware family already observed in this dataset, linking outside research to
    what the pipeline independently discovered."""
    reports = session.scalars(
        select(OsintReportRecord).order_by(OsintReportRecord.published_at.desc()).limit(limit)
    ).all()
    lines = [
        "## Recent OSINT Reporting",
        "",
        "Latest posts from Unit 42, The DFIR Report, and CISA advisories. Run "
        "`threat-ingest osint-sync` to refresh.",
        "",
    ]
    if not reports:
        lines.extend(["_No OSINT reports synced yet._", ""])
        return lines

    lines.extend(["| Source | Title | Mentions | Published |", "|---|---|---|---|"])
    for report in reports:
        haystack = f"{report.title} {report.summary}".lower()
        mentioned = sorted(family for family in families if family.lower() in haystack)
        mentions = ", ".join(mentioned) or "-"
        title = f"[{report.title.replace('|', chr(92) + '|')}]({report.link})"
        lines.append(f"| {report.source} | {title} | {mentions} | {report.published_at.date().isoformat()} |")
    lines.append("")
    return lines


def _attack_section(correlation_rows: list[tuple[str, int, str, str, str]]) -> list[str]:
    """Maps correlated malware families to MITRE ATT&CK techniques via the local
    curated mapping, turning "these indicators cluster together" into "this
    cluster exhibits these behaviors and techniques"."""
    lines = [
        "## MITRE ATT&CK Techniques Observed",
        "",
        "Techniques associated with the malware families seen above, via a curated "
        "local mapping (see `attack_mapping/mapping.py`).",
        "",
    ]
    technique_families: dict[str, dict[str, Any]] = {}
    for family, _count, _sources, _types, _top_tags in correlation_rows:
        if family == "unlabeled":
            continue
        for technique in techniques_for_family(family):
            entry = technique_families.setdefault(
                technique.technique_id, {"name": technique.name, "tactic": technique.tactic, "families": set()}
            )
            entry["families"].add(family)

    if not technique_families:
        lines.extend(["_No mapped malware families observed yet._", ""])
        return lines

    lines.extend(["| Technique | Tactic | Malware Families |", "|---|---|---|"])
    for technique_id, entry in sorted(technique_families.items()):
        families = ", ".join(sorted(entry["families"]))
        lines.append(f"| {technique_id} {entry['name']} | {entry['tactic']} | {families} |")
    lines.append("")
    return lines


def build_report(session: Session, recent_limit: int = 20) -> str:
    indicators = session.scalars(select(IndicatorRecord)).all()
    observations = session.scalars(
        select(ObservationRecord).order_by(ObservationRecord.observed_at.desc())
    ).all()
    runs = session.scalars(select(CollectionRunRecord).order_by(CollectionRunRecord.started_at.desc())).all()
    attempts = session.scalars(select(RunSourceAttemptRecord)).all()

    indicator_by_id = {indicator.id: indicator for indicator in indicators}
    source_counts = Counter(observation.source for observation in observations)
    type_counts = Counter(
        indicator_by_id[observation.indicator_id].indicator_type
        for observation in observations
        if observation.indicator_id in indicator_by_id
    )
    family_counts: Counter[str] = Counter()
    tag_counts: Counter[str] = Counter()
    for observation in observations:
        metadata: dict[str, Any] = observation.metadata_json or {}
        family = metadata.get("malware") or metadata.get("malware_family")
        if family:
            family_counts[str(family)] += 1
        tags = metadata.get("tags") or []
        if isinstance(tags, list):
            tag_counts.update(str(tag) for tag in tags if tag)

    successful_attempts = sum(attempt.status == "success" for attempt in attempts)
    failed_attempts = sum(attempt.status == "failed" for attempt in attempts)
    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    lines = [
        "# Threat Intelligence Report",
        "",
        f"Generated: `{generated_at}`",
        "",
        "## Overview",
        "",
        f"- Indicators: **{len(indicators)}**",
        f"- Observations: **{len(observations)}**",
        f"- Collection runs: **{len(runs)}**",
        f"- Source attempts: **{len(attempts)}** ({successful_attempts} successful, {failed_attempts} failed)",
        "",
    ]
    lines.extend(_markdown_table(_top_rows(source_counts), "Observations by Source"))
    lines.extend(_markdown_table(_top_rows(type_counts), "Indicators by Type"))
    lines.extend(_markdown_table(_top_rows(family_counts), "Top Malware Families"))
    lines.extend(_markdown_table(_top_rows(tag_counts), "Top Tags"))

    lines.extend(
        [
            "### Correlation Clusters",
            "",
            "Clusters group observations by malware family and show their source and IOC-type spread.",
            "",
            "| Family | Observations | Sources | IOC Types | Top Tags |",
            "|---|---:|---|---|---|",
        ]
    )
    for family, count, sources, indicator_types, top_tags in _correlation_rows(
        observations, indicator_by_id
    ):
        lines.append(
            f"| {family.replace('|', '\\|')} | {count} | {sources} | {indicator_types} | {top_tags} |"
        )
    lines.append("")

    correlation_rows = _correlation_rows(observations, indicator_by_id)
    lines.extend(_attack_section(correlation_rows))
    lines.extend(_cluster_section(session, indicator_by_id))
    lines.extend(_kev_section(session))
    lines.extend(_exposed_kev_section(session, indicator_by_id))
    lines.extend(_osint_section(session, {family for family, *_ in correlation_rows if family != "unlabeled"}))

    lines.extend(["## Recent Observations", "", "| Source | Type | Indicator | Observed At |", "|---|---|---|---|"])
    for observation in observations[:recent_limit]:
        indicator = indicator_by_id.get(observation.indicator_id)
        value = indicator.canonical_value if indicator else "unknown"
        indicator_type = indicator.indicator_type if indicator else "unknown"
        lines.append(
            f"| {observation.source} | {indicator_type} | `{value.replace('`', '')}` | {observation.observed_at.isoformat()} |"
        )
    lines.append("")
    return "\n".join(lines)


def write_report(session: Session, output_path: str, recent_limit: int = 20) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_report(session, recent_limit=recent_limit), encoding="utf-8")
    return path
