#!/usr/bin/env python3
"""
Test script for Google Docs export functionality.

Usage:
    python test_google_docs.py              # Test with sample content
    python test_google_docs.py validate     # Validate setup only
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv


load_dotenv(Path(__file__).with_name(".env"))


def test_credentials():
    """Test that credentials can be loaded."""
    print("\n1️⃣  Testing Google Credentials...")

    creds_path = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
    if creds_path:
        creds_file = Path(creds_path)
        if not creds_file.exists():
            print(f"   ❌ Credentials file not found: {creds_file.absolute()}")
            return False
        print(f"   ✅ Found credentials file: {creds_file.name}")
        return True

    try:
        import google.auth
        credentials, project_id = google.auth.default(scopes=["https://www.googleapis.com/auth/documents"])
        print("   ✅ Found Application Default Credentials via gcloud or managed identity.")
        print(f"   📌 Project: {project_id or 'unknown'}")
        return credentials is not None
    except Exception as e:
        print("   ❌ GOOGLE_APPLICATION_CREDENTIALS not set and no ADC credentials were found.")
        print(f"   ℹ️  Details: {e}")
        return False


def test_api_connection():
    """Test connection to Google Docs API."""
    print("\n2️⃣  Testing Google Docs API Connection...")

    doc_id = os.getenv("GOOGLE_DOC_ID")
    if not doc_id:
        print("   ❌ GOOGLE_DOC_ID not set")
        return False

    print(f"   📄 Document ID: {doc_id[:30]}...")

    try:
        from googleapiclient.discovery import build
        import google.auth

        creds_path = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
        if creds_path:
            from google.oauth2.service_account import Credentials
            credentials = Credentials.from_service_account_file(
                creds_path,
                scopes=["https://www.googleapis.com/auth/documents"]
            )
        else:
            credentials, _ = google.auth.default(scopes=["https://www.googleapis.com/auth/documents"])

        service = build("docs", "v1", credentials=credentials)
        doc = service.documents().get(documentId=doc_id).execute()

        print(f"   ✅ Connected! Document title: \"{doc.get('title')}\"")
        return True

    except Exception as e:
        print(f"   ❌ Connection failed: {e}")
        return False


def test_export():
    """Test actual export functionality."""
    print("\n3️⃣  Testing Export Functionality...")
    
    try:
        from gtm_project.exporters import export_to_google_docs
        
        sample_content = """## Test GTM Strategy

This is a test export from the CrewAI workflow.

### Market Opportunity
- Testing Google Docs integration
- Verifying content formatting
- Confirming real-time collaboration

### Go-To-Market Plan
1. Verify credentials work
2. Test document append
3. Validate formatting

### Timeline
- Week 1: Setup
- Week 2: Testing
- Week 3: Production

---
*Generated by CrewAI Multi-Agent Workflow*
*Exported: 2026-08-27*
"""
        
        result = export_to_google_docs(sample_content)
        
        if result.get("status") == "exported":
            doc_id = result.get("document_id")
            print(f"   ✅ Export successful!")
            print(f"   📄 Document ID: {doc_id}")
            print(f"   🔗 URL: https://docs.google.com/document/d/{doc_id}/edit")
            return True
        else:
            print(f"   ⚠️  Export status: {result.get('status')}")
            print(f"   ℹ️  Details: {result.get('detail')}")
            return False
    
    except Exception as e:
        print(f"   ❌ Export test failed: {e}")
        import traceback
        traceback.print_exc()
        return False


def main():
    """Run all tests."""
    if len(sys.argv) > 1 and sys.argv[1] == "validate":
        # Just validate, don't export
        all_pass = test_credentials() and test_api_connection()
    else:
        # Run full test
        all_pass = (
            test_credentials() and
            test_api_connection() and
            test_export()
        )
    
    print("\n" + "=" * 70)
    if all_pass:
        print("✅ All tests passed! Google Docs export is ready.")
        print("\nYou can now:")
        print("  1. Run: uv run python src/gtm_project/main.py --domain fintech --mode crewai")
        print("  2. Or use the Streamlit chatbot: python -m streamlit run src/gtm_project/chatbot.py")
        print("\nThe strategy will be automatically exported to your Google Doc.")
    else:
        print("❌ Some tests failed. See above for details.")
        print("\nTo fix the setup:")
        print("  1. Run: python setup_google_docs.py")
        print("  2. Follow the interactive prompts")
        print("  3. Run this test again")
    print("=" * 70)
    
    return 0 if all_pass else 1


if __name__ == "__main__":
    sys.exit(main())
